language: android
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-support
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_26602ca85943_key -iv $encrypted_26602ca85943_iv -in omron/release-key.keystore.enc -out omron/release-key.keystore -d
- git clone https://github.com/MD2Korg/mCerebrum-Utilities.git /home/travis/build/MD2Korg/mCerebrum-Utilities
- git clone https://github.com/MD2Korg/mCerebrum-DataKitAPI.git /home/travis/build/MD2Korg/mCerebrum-DataKitAPI
script:
- "./gradlew assembleRelease"
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: WqfQR3Ptm+NhMB2twaTwVo1FJBZg7a+tbrkl/SZa9tJJIz59fHJELiGa9OmASk7L712w8aM4l/zZHpCynEscuMRsSuFJZP96zQ27aB2Z1PhLyROXxTiEAyuE3zbJw8dXp0kG+G6JjhJta49q4sQGzne15qH+6mAKVFogOAMZ0RnT7wu/BdHwKxA1WWIlALb8PpkSzidG5QIouJ/lhuETNN0dQhYD8jnN44COgjcf6Fx6HckuMwLQKWr2j6KUs7eVfb54gKr0Bt/PA7xopGfJ6CFrVd28THglsGBkyUwEi4/a59EbdSxW82jDM7Oq7t7ytHJSGadLbBkAuxbNa5Uom/4qV17sJNti3NvLI+ZvKwVHiAVEScFi0Rac9m3m6uJvVAboYrrnxU6LMNSB1Loc4kr0TsfFWfoQc4V0UhVt+J+Yyyzn25v13bv9cjywJAn0CHWUwEpD597qLIwrEN1V+pmSaRDVbJw5yvHcRlt87bW+kiSCZ1GjVMa/NU5gp2I6+gzIPzHQ0MU3tn7mWoZ2aaSrOebW6AreGCovo+QtVzNI4hJrlNHJqohDpUTAKXz2OWd68Imu4PQlikbNA2dDV7Y6wVzx9xtR/sYWYedVZBAf0sRv1LAflQogskmzAtU12n65mOQuXoCqq3y9F6rcwHTIeYHn/LH+g1WQnwLng4k=
  file: omron/build/outputs/apk/omron*.*.*.apk
  on:
    repo: MD2Korg/mCerebrum-Omron
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: qe/CqLi9su+BRKpVDlcOX1Tlb+kMnc/fCFieAFnijvnZpenHLRgIiwELH5YL8Qu1AwRVJuNVVBJGDaYxCgdNSAMyQv/zTXJhxw87HKkdDSlTFiSM1ruI4THdagw7nDYYsmBRC4OTkU4wqIRsSlGrH09bCXI/Q77vOMFQRW5Ddc1JlK4to4LvUTOwqY9fatS9Bc2buQ3QTkYtAltTr65Eu6eCDgBIpwM4YKrvjeyZVgklkYRXr2ndY7nc2WptOpavbpNqSST4SIjWeRX+70i6UJY1z/E56ppgIxAtH3qfNatI9KXRWob3+3SN6W/khin3w/IWYLJYjS8RFHwCq5yVnTngOTWtlyEqy1qLkwqYf1qlbCxd7087lMhFiIciTFkubN5riZMe9pg1aBnBQ3Q3DYV3C3fWvRpDYYMfT5RMEdhwp6viYH8Qf9n71Qi/6eiApyExZU4eaH8U1I8T1uQduBK2jOynJWqIz1YW8aMGEQ8/UrQ/loutd49l75bGqjAjG90+Fmlo3BGZ3nslNkK8NR6gjf+Jp/RVIFDZC0f7z6EvAd8bQ5BO/+2/2bRrvTCB6SzJcOtXXKJ5uOU6x4MpjUGoaX6yJ1L/JNp58/MP8quLn/rg+vrn9A+MZxzaRd+ZGjWqCvATS6dyMP4Gv19N0jp/EyPFhVGzVyVthX/Rz88=
  - secure: IXzyDNtD2nWM9huuUELFTdQkOryWNbhaxpmNLCJ1oE8Gy709mA4Bb/LGmaYozjHtq1uR/BSUCCsv73BZOz9uVoVWtcF1kS0gaoqfdltDWI81ndeKIW0TvY1Xw11K93lVkTlJaIpy8NWrbAG3rUPq4QqNr7pxWmktwZ91CDjkgVZUFMGCPY4+6sLJcP/SYAzlIUrwiNfhSigl/P2jwNVu4wUqp2g1AOQcV8X2kLUtQgIrDd0GJP8HyhozPqy2WyM75Mz/RShfT6lgzl2HR5mJs4GqfsU2HjOK4KL22N98uDq8W4usdtZqqWoQfmCBm1nNFA96GeTMF3d1Vxg7M/YZbZiBHrx+/6iRatN7vsu2INZtkW1ye3Dl+TWFkLmv9M9YiwvdM2w7KElgM193Rn2Iuj5M0WqX08GvsE6pczSmCEaKS5esx4qRQNBYkCkU7CWXsp6Wf/cIEeRtOJdwOvyT3/OtBW0Fvntaf+5lP7cUmM32VUhWJQaEXnHEPeoQoaOITScFEEX4y6MCGzWTmbIPGvdVhtZBXxf5+taNp7RS/DRpV9a7takiqmTCbhF6me8DO6lhRltwR+VqF6izCEPTjnfBpCXgCPlBjdgLoQKxg7fmVmO1sMYC3FKaHrvAwT5pDbxSkzchkl5X7To5CuRgjq1IMyUDPQo/Eu84tvv+8Kg=
  - secure: G7hykd1pJk2mzI05Ue6jsO/V95/AZ+032w4D4BfHMbY5yQlSpHx6s1t3pmZJk+9qYlG55Y0x1Q9EujRd6EmwrOdRNR84D6zRr6jebym2z6W2xj//RooEXwadtFN0ziseusK8uoqzK6jdueyWrbLEpzWJ0/PycMW3kzq8fE1jfJ0qRybHH4oVAQsgL/p4x8FuKoJIEXaO6wNkrne9UosF+Q833ir4YbPr1zp/iiX5rgG8jaJlRgkYpLCVSA41y88/lLipP0seHVBM43WvqCeFkdF4FnaF1yspboyTuOQISVIsUcweP/ZyczU1cEDvEUZoITpixBsHhqS13e4jtwm7MkBiX4engh9X7vIVypHrF6HxOeSOztb4DIL66WHNEj3UbzHB0nHmvrJ7i91Tc5pNjT7t8tx/B34qRZODQ9IsC1pWrze14SFiDtaisRlmuoECdWu0bkRz1duHEBD87dbgF0Fe2t0y+InuoLkC4lgaOqN+mfpbKr+EDk0CyucZiuLqT8mFMq0Z12cHWv7IqVPnGAqIBOZOO0ZRPyURYdWi7qST7c+v2G9bGsyGlei9tKCMcJzCQa5RiHX++TeG53OsVbufebEg6DnzZipuZV2ZW2qpRuEe3yKZwyD+iosXBCzamYo20Ye3VAbHu6Uon+VELrAzKoJGNV0Q/842P+rxXKE=
  - secure: dOnQUvhmXtmBl+xY5f5vzie6YhBgIRHGRG4aHlTofYO0CI8Tx5xJ/zPpP33mT1AwHKmAleKLagneMKH80p0pVgV5esRVuvnfCKvMKPFaq+WrhGFRi4wWVTkq1zk6Qf4AWIXD2BgU+6qLzXX5HowF3uEkq+aBXhG5dFUradqtZSuWV3TjVxhlzIyIWNX1BmKiVIwCfMA5U4+nWk7uxTn5lRQ6+A5/pguKr7kKuiPFEjaM4jjeC/E2F7skb6sXnXsXC3WSovhRSrPj8XsiY8Lomu1lZ1sJnGDCcC+1h2VSBYBSARZ8H64sYJd0hXYTccurVJxjglviRqrQaJhBFNLAX3KMb1VmKdu90rmEiFccrQoI/ZHnHwz7qJ0lc3GxRVESPt6TezPhmKg8pDvB8fyHyNkrGA7BQijmE8pYZJuNPbh3IjfA8wKhiTpBYLHbgODuyux4Q9FAZB2y6FTaz/hIougtr7VuHFQq4fOtRsiEr+z6lyPp/Nu4T6QKmHN671KRQuXL9RJbN1K98hCmSq8fVaJWmD/jSETcd4AuwH6tuKWe3+0yudS4IM8Rw22PulONFEt2fl2KtR+iFPj1mGyp9u4PcvuZqiiJXQSKr94xxyS4gLnCC0MoHPZxoeahDd0Ckf3XxURC8jq6O6Kp4nMZwwl/3qXkYYbW0IbUs8gmKhY=
